[tool.poetry]
name = "dbplot"
version = "0.1.0"
description = ""
authors = ["Daniel Rodriguez <df.rodriguez143@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"
ibis-framework = "^0.14"

[tool.poetry.dev-dependencies]
pytest = "^3.4"
